#!/usr/bin/env python3
"""
glue.py -- the reserved-word list, generated rather than remembered.

R5: a multi-word name may not contain any word appearing AFTER THE FIRST HOLE
of an in-scope pattern. Those words -- the glue -- are therefore reserved, and
the union of every in-scope pattern's glue IS the language's reserved-word
list. Nothing writes it down today, which means:

  * nobody can see the cost of adding a pattern before adding it
  * R5's diagnostic cannot say WHICH pattern reserved the word
  * adding a stdlib pattern silently invalidates user names in every program
    that imports it, and no test notices

So: compute it, check it in, and fail the build when it changes.

    python3 glue.py               emit the registry
    python3 glue.py --check FILE  compare against a checked-in registry

The anchor run is the words BEFORE the first hole. They are matched before any
hole is opened, so no name can straddle them and they reserve NOTHING. That is
the design lever: a pattern with all its words up front is free.
"""

import sys
from collections import defaultdict

HOLE = '_'


def parse(path):
    out = []
    for raw in open(path):
        line = raw.split('#')[0].strip()
        if not line:
            continue
        module, _, pat = line.partition('|')
        words = pat.split()
        if words:
            out.append((module.strip(), tuple(words)))
    return out


def anchor_and_glue(pat):
    """Anchor run = words before the first hole. Glue = literal words after it.

    Judged by POSITION, never by word value. Judging by value leaves the second
    «b» of «b b (_)» unreserved, which the fuzzer caught and inspection did
    not."""
    run = 0
    while run < len(pat) and pat[run] != HOLE:
        run += 1
    return pat[:run], tuple(w for w in pat[run:] if w != HOLE)


def build(decls):
    reserved = defaultdict(list)          # word -> [(module, pattern)]
    free = []
    for module, pat in decls:
        anchor, glue = anchor_and_glue(pat)
        if not glue:
            free.append((module, pat, anchor))
        for w in glue:
            reserved[w].append((module, pat))
    return reserved, free


def show(pat):
    return ' '.join('(_)' if w == HOLE else w for w in pat)


def render(decls):
    reserved, free = build(decls)
    modules = sorted({m for m, _ in decls})
    L = []
    L.append('# GLUE REGISTRY -- GENERATED BY glue.py, DO NOT EDIT')
    L.append('#')
    L.append('# Every word below is RESERVED inside multi-word names in any scope where')
    L.append('# the causing pattern is visible. This is the language\'s reserved-word list.')
    L.append('#')
    L.append('# Adding a line here is a BREAKING CHANGE for every program that imports the')
    L.append('# module: names that were legal stop being legal. Review accordingly.')
    L.append('')

    prelude = {w: v for w, v in reserved.items()
               if any(m == 'prelude' for m, _ in v)}
    L.append('## ALWAYS RESERVED (prelude -- in scope everywhere, no escape)')
    L.append('')
    if not prelude:
        L.append('    (none)')
    for w in sorted(prelude):
        for m, p in sorted(reserved[w]):
            if m == 'prelude':
                L.append(f'    {w:<12} {show(p):<34} {m}')
    L.append('')

    L.append('## RESERVED ON IMPORT (only in scopes that import the module)')
    L.append('')
    any_mod = False
    for mod in modules:
        if mod == 'prelude':
            continue
        rows = [(w, p) for w in sorted(reserved)
                for m, p in reserved[w] if m == mod]
        if not rows:
            continue
        any_mod = True
        L.append(f'  {mod}')
        for w, p in rows:
            L.append(f'    {w:<12} {show(p):<34} {mod}')
        L.append('')
    if not any_mod:
        L.append('    (none)')
        L.append('')

    L.append('## RESERVES NOTHING (all words precede the first hole -- the shape to prefer)')
    L.append('')
    for m, p, a in sorted(free):
        L.append(f'    {show(p):<34} anchor «{" ".join(a)}»' if a
                 else f'    {show(p):<34} (no words)')
    L.append('')

    L.append('## RESERVED BY A SINGLE PATTERN (respell it and the word is free again)')
    L.append('')
    singles = sorted((w, v[0]) for w, v in reserved.items() if len(v) == 1)
    for w, (m, p) in singles:
        L.append(f'    {w:<12} {show(p):<34} {m}')
    L.append('')

    L.append('## POSTFIX PATTERNS (leading hole -- EVERY word is glue, most expensive shape)')
    L.append('')
    post = [(m, p) for m, p in decls if p and p[0] == HOLE]
    for m, p in sorted(post):
        L.append(f'    {show(p):<34} {m}')
    if not post:
        L.append('    (none)')
    L.append('')

    L.append('## SUMMARY')
    L.append('')
    L.append(f'    patterns declared        {len(decls)}')
    L.append(f'    reserve nothing          {len(free)}')
    L.append(f'    distinct reserved words  {len(reserved)}')
    L.append(f'    always reserved          {len(prelude)}  '
             f'({", ".join(sorted(prelude)) or "none"})')
    return '\n'.join(L) + '\n'


if __name__ == '__main__':
    decls = parse('stdlib-proposal.txt')
    text = render(decls)
    if '--check' in sys.argv:
        want = open(sys.argv[sys.argv.index('--check') + 1]).read()
        if want == text:
            print('glue registry up to date')
            sys.exit(0)
        print('GLUE REGISTRY OUT OF DATE.\n')
        print('A pattern was added, removed or respelled, which changes the set of')
        print('words programmers may not use inside multi-word names. Regenerate and')
        print('review the diff -- every added line breaks existing user code.\n')
        import difflib
        for line in difflib.unified_diff(want.splitlines(), text.splitlines(),
                                         'checked-in', 'computed', lineterm=''):
            print(' ', line)
        sys.exit(1)
    sys.stdout.write(text)
