#!/usr/bin/env python3
"""
ledger.py -- the live-verdict index, generated rather than remembered.

Every design memo and ruling in this folder opens with a ledger header
(see LEDGERSCHEMA.md): a marker `[V]`/`[R]`, a one-line summary, and the two
supersession fields. This walks those headers and emits the one page a successor
actually wants -- what currently binds -- and reports any design document whose
header is missing or malformed, so a broken header is a visible defect in a
generated artefact rather than an invisible one in a file nobody opened
(LEDGERRULING §7).

    python3 ledger.py             emit the index
    python3 ledger.py --check F   compare against a checked-in index; nonzero on drift

Audit reports (REAUDIT*, AUDIT*, FRESHAUDIT*, CODEREVIEW) keep their native
format and carry disposition, not supersession, so they are not expected to have
a header (LEDGERRULING §4). Scripts are skipped by the .md glob. Everything else
is a design document and must have one.
"""

import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
GENERATED = "LEDGER.md"                       # this script's own output; never a source

AUDIT = re.compile(r"^((RE)?AUDIT|FRESHAUDIT|CODEREVIEW)")
LEDGER_LINE = re.compile(r"^> \*\*Ledger\*\* — ")
MARKER = re.compile(r"`\[(V|R)\]`")
SUPERSEDES = re.compile(r"^> supersedes: (.+?)\s*$")
SUPERSEDED_BY = re.compile(r"^> superseded by: (.+?)\s*$")
UNWALKED = "not yet checked"
LEGAL_ABSENT = {"none", UNWALKED}


class Doc:
    def __init__(self, name):
        self.name = name
        self.marker = None            # 'V' | 'R' | None
        self.summary = ""
        self.supersedes = None        # field value or None if the line is absent
        self.superseded_by = None
        self.defects = []             # list of strings

    @property
    def is_audit(self):
        return bool(AUDIT.match(self.name))

    @property
    def unwalked(self):
        return self.supersedes == UNWALKED or self.superseded_by == UNWALKED


def header_block(lines):
    """The consecutive '>' lines of the leading ledger blockquote, or None."""
    start = next((i for i, ln in enumerate(lines) if LEDGER_LINE.match(ln)), None)
    if start is None:
        return None
    end = start
    while end < len(lines) and lines[end].startswith(">"):
        end += 1
    return lines[start:end]


def parse(path):
    doc = Doc(path.stem)
    lines = path.read_text(encoding="utf-8").splitlines()
    block = header_block(lines)

    if block is None:
        if not doc.is_audit:
            doc.defects.append("no ledger header")
        return doc

    marker = MARKER.search(block[0])
    doc.marker = marker.group(1) if marker else None
    if doc.marker is None:
        doc.defects.append("header has no `[V]`/`[R]` marker")

    summary = []
    for ln in block:
        if SUPERSEDES.match(ln) or SUPERSEDED_BY.match(ln):
            continue
        summary.append(ln.lstrip("> ").rstrip())
    doc.summary = MARKER.sub("", " ".join(summary), count=1).replace("**Ledger** — ", "").strip()

    for ln in block:
        m = SUPERSEDES.match(ln)
        if m:
            doc.supersedes = m.group(1)
        m = SUPERSEDED_BY.match(ln)
        if m:
            doc.superseded_by = m.group(1)

    for field, value in (("supersedes", doc.supersedes), ("superseded by", doc.superseded_by)):
        if value is None:
            doc.defects.append(f"missing `{field}` field")
        elif not value or value == "nothing":
            doc.defects.append(f"`{field}` has an illegal value ({value!r}; use `none` or `not yet checked`)")
    return doc


def collect():
    docs = []
    for path in sorted(HERE.glob("*.md")):
        if path.name == GENERATED:
            continue
        docs.append(parse(path))
    return docs


def bullet(doc, tail=""):
    summary = (doc.summary[:96] + "…") if len(doc.summary) > 97 else doc.summary
    return f"- **{doc.name}** — {summary}{tail}"


def render(docs):
    design = [d for d in docs if not d.is_audit]
    clean = [d for d in design if not d.defects]

    verdicts_live = [d for d in clean if d.marker == "V" and d.superseded_by == "none"]
    verdicts_open = [d for d in clean if d.marker == "V" and d.superseded_by == UNWALKED]
    verdicts_gone = [d for d in clean if d.marker == "V" and d.superseded_by not in LEGAL_ABSENT]
    recommendations = [d for d in clean if d.marker == "R"]
    worklist2 = [d for d in clean if d.unwalked]
    worklist1 = [d for d in design if "no ledger header" in d.defects]
    defective = [d for d in design if d.defects and "no ledger header" not in d.defects]

    out = []
    out.append("# Ledger — what currently binds")
    out.append("")
    out.append("Generated by `ledger.py` from the headers in `docs/handoff`. Do not edit by")
    out.append("hand — run `python3 ledger.py` to regenerate.")
    out.append("")
    out.append(
        f"{len(design)} design documents · {len(clean)} with a ledger header · "
        f"{len(worklist1)} awaiting one · {len([d for d in docs if d.is_audit])} audit reports (excluded)."
    )

    out.append("")
    out.append("## Verdicts in force")
    out.append("")
    out += [bullet(d) for d in verdicts_live] or ["_none_"]

    if verdicts_open:
        out.append("")
        out.append("## Verdicts — supersession not yet checked")
        out.append("")
        out += [bullet(d) for d in verdicts_open]

    if verdicts_gone:
        out.append("")
        out.append("## Superseded verdicts")
        out.append("")
        out += [bullet(d, f"  (superseded by: {d.superseded_by})") for d in verdicts_gone]

    out.append("")
    out.append("## Recommendations")
    out.append("")
    out += [bullet(d) for d in recommendations] or ["_none_"]

    out.append("")
    out.append(f"## Pass 2 worklist — supersession not yet checked ({len(worklist2)})")
    out.append("")
    out += [f"- **{d.name}**" for d in worklist2] or ["_none_"]

    out.append("")
    out.append(f"## Pass 1 worklist — design documents with no ledger header ({len(worklist1)})")
    out.append("")
    out += [f"- {d.name}" for d in worklist1] or ["_none_"]

    if defective:
        out.append("")
        out.append("## Defects")
        out.append("")
        for d in defective:
            out += [f"- **{d.name}** — {problem}" for problem in d.defects]

    out.append("")
    return "\n".join(out)


def main(argv):
    docs = collect()
    index = render(docs)

    if len(argv) >= 2 and argv[0] == "--check":
        current = Path(argv[1]).read_text(encoding="utf-8")
        if current != index:
            sys.stderr.write(f"{argv[1]} is out of date; run `python3 ledger.py` and commit.\n")
            return 1
        return 0

    sys.stdout.write(index)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
