#!/usr/bin/env python3
"""
r7b_generator.py -- is R7b's word set really {a, an}, with R6b picking up «not»?

His hypothesis: «not (_)» is anchor-only, so once it is declared R6b already
refuses names beginning «not», and R7b's generated set reduces to the words that
refine a hole into the TYPE table -- {a, an}. One rule, one job.

The outcome is the same today. The REASON is not, and that is worth measuring
before the set is trimmed, because ARTICLECONDITIONAL.md §1 found «not x»
breaking with NO «not (_)» pattern present at all:

    base               x is not x    OK
    + name «not x»     x is not x    TIE -> ERROR

That tie comes from «(_) is not (_)» refining «(_) is (_)» at a hole boundary.
If R7b drops «not» because R6b covers it, the safety of the is/is-not pair
becomes contingent on an unrelated pattern continuing to exist.

Two parts: a generator from the refinement relation, and an exhaustive sweep to
check the generated set is complete.
"""

import itertools
from dp_resolver import DPResolver, N, PA, HOLE

W = 78


def res(names, pats, src):
    v, c, s = DPResolver(names, pats).resolve(src)
    return v, s


def wordcontent(p):
    return tuple(s for s in p if s is not HOLE)


def anchor_only(pats):
    return [wordcontent(p) for p in pats
            if p[-1] is HOLE and all(s is not HOLE for s in p[:-1])]


def refines(p, q):
    """Is q obtainable from p by inserting one or more literal words
    IMMEDIATELY at the start of one of p's free holes? If so, yield the first
    inserted word."""
    out = []
    for hi, seg in enumerate(p):
        if seg is not HOLE:
            continue
        # q must equal p[:hi] + <words> + p[hi:]
        pre = p[:hi]
        if len(q) <= len(p) or q[:hi] != pre:
            continue
        k = len(q) - len(p)
        inserted = q[hi:hi + k]
        if any(s is HOLE for s in inserted):
            continue
        if q[hi + k:] == p[hi:]:
            out.append(inserted[0])
    return out


def generate(pats):
    words = set()
    for p in pats:
        for q in pats:
            if p is q:
                continue
            words.update(refines(p, q))
    return words


IS_FAMILY = PA('_ is _', '_ is a _', '_ is an _', '_ is not _',
               '_ is not a _', '_ is not an _')
WITH_NOT = IS_FAMILY | PA('not _')

print('=' * W)
print('1. The generator, from the refinement relation')
print('=' * W)
for label, pats in (('is family only', IS_FAMILY), ('+ «not (_)»', WITH_NOT)):
    gen = generate(pats)
    anch = anchor_only(pats)
    print(f'  {label:16}  R7b generated = {sorted(gen)}')
    print(f'  {"":16}  R6b anchor-only word runs = '
          f'{[" ".join(a) for a in anch]}')
print('''
  «not» is generated by the refinement relation in BOTH configurations, because
  «(_) is not (_)» refines «(_) is (_)» whether or not a «not (_)» pattern
  exists. R6b only covers it in the second.''')

print('=' * W)
print('2. Exhaustive: which name-initial words actually break something?')
print('=' * W)
UNI = ['x', 'is', 'not', 'a', 'number']
BASE = N('x', 'number')
SRCS = [s for k in range(1, 6) for s in itertools.product(UNI, repeat=k)]


def sweep(pats, label):
    before = {}
    for s in SRCS:
        v, sh = res(BASE, pats, ' '.join(s))
        if v == 'OK':
            before[s] = sh
    anch = anchor_only(pats)
    dangerous_initials = set()
    for k in (2, 3):
        for c in itertools.product(UNI, repeat=k):
            if c in BASE:
                continue
            # exclude names R5' already refuses (interior glue)
            glue = set()
            for p in pats:
                seen = False
                for seg in p:
                    if seg is HOLE:
                        seen = True
                    elif seen:
                        glue.add(seg)
            if any(0 < i < len(c) - 1 and w in glue for i, w in enumerate(c)):
                continue
            names = BASE | {c}
            for s, bs in before.items():
                av, asw = res(names, pats, ' '.join(s))
                if av != 'OK' or asw != bs:
                    dangerous_initials.add((c[0], any(
                        len(a) < len(c) and c[:len(a)] == a for a in anch)))
                    break
    print(f'  {label}')
    print(f'      sources parsing before any new name: {len(before)}')
    for w, by_r6b in sorted(dangerous_initials):
        print(f'      names beginning «{w}» break something   '
              f'(covered by R6b: {by_r6b})')
    return {w for w, _ in dangerous_initials}


emp1 = sweep(IS_FAMILY, 'is family only, no «not (_)»')
emp2 = sweep(WITH_NOT, 'with «not (_)» declared')
print()
gen1, gen2 = generate(IS_FAMILY), generate(WITH_NOT)
for label, emp, gen in (('is family only', emp1, gen1),
                        ('with «not (_)»', emp2, gen2)):
    missing = emp - gen
    print(f'  {label:18} empirical {sorted(emp)}   generated {sorted(gen)}   '
          f'{"MATCH" if not missing else "MISSING " + str(sorted(missing))}')

print(f'''
=' {"=" * (W - 2)}
3. What this means for the trim
{"=" * W}
  The hypothesis is right about COVERAGE and wrong about REASON.

  With «not (_)» declared, R6b does refuse names beginning «not», so trimming
  R7b to {{a, an}} changes no outcome today. But the hazard R7b exists for is
  present WITHOUT «not (_)» -- the is/is-not pair alone creates it. So a trim
  makes the safety of «(_) is not (_)» contingent on an unrelated pattern
  continuing to exist. Respell negation as a symbol later, and the hazard comes
  back with no rule watching it.

  That is the same "invariant enforced by coincidence" shape this audit round
  has turned up three times, and it costs nothing to avoid: GENERATE the set
  from the refinement relation, and let R6b and R7b overlap on «not».

  His diagnostic worry -- "a reader having to work out which fired" -- is real
  and has a better fix than trimming: report the CAUSES, not the rule.

      «not x» cannot be declared:
          «not (_)» would be shadowed by it
          «(_) is not (_)» refines «(_) is (_)», so a name beginning «not»
          can absorb the difference

  Rule names are for us. Pattern names are for the programmer, and two causes
  is information rather than confusion -- it tells them removing one pattern
  will not free the name.''')
