<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <AssemblyName>Ronin.Program</AssemblyName>
    <RootNamespace>Ronin.Program</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Parser\Parser.csproj" />
  </ItemGroup>

</Project>
